version: '3.9'

services:
  dev-node:
    image: 'node:17-alpine3.14'
    working_dir: '/home/dev-node'
    volumes:
      - ./:/home/dev-node
    command: "sh -c 'npm i && npm run start:dev ' "
    depends_on:
      - dev-db-pg
    environment:
      NODE_ENV: development
      POSTGRES_HOST: dev-db-pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 3000:3000
  dev-db-pg:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: dev-db-pg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
