version: '3.8'

services:
  task3-node:
    image: 'node:16.14.2-alpine3.14'
    working_dir: '/home/task3-node'
    volumes:
      - ./:/home/task3-node
    command: "sh -c 'npm i && npm i -g @nestjs/cli && npm run start:dev ' "
    depends_on:
      - task3-postgres
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  task3-postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task3-postgres
