PATCH http://localhost:3000/notes/2/archived
Content-Type: application/json

###
PATCH http://localhost:3000/notes/2
Content-Type: application/json

{
  "title": "title pdate4",
  "content": "some 05.15.2020 05/15/2020 update",
  "categoryId": 3,
  "archived": true
}

###
DELETE http://localhost:3000/notes/19
Accept: application/json

###
POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "react 2",
  "content": "some 05.15.2020",
  "categoryId": 2
}

###
POST http://localhost:3000/notes/category
Content-Type: application/json

{
  "name": "Random quote"
}

###
GET http://localhost:3000/notes/3
Accept: application/json

###
GET http://localhost:3000/notes
Accept: application/json

###

GET http://localhost:3000/notes/stats
Accept: application/json

###


GET http://localhost:3000/notes/categories
Accept: application/json

###
