PATCH http://localhost:3000/notes/2/archived
Content-Type: application/json

###
PATCH http://localhost:3000/notes/2
Content-Type: application/json

{
  "title": "title update",
  "content": "some 05.15.2020 update",
  "categoryId": 3,
  "archived": true
}

###
DELETE http://localhost:3000/notes/1
Accept: application/json

###
POST http://localhost:3000/notes
Content-Type: application/json

{
  "title": "one lolo ",
  "content": "some 05.15.2020",
  "categoryId": 3
}

###
GET http://localhost:3000/notes/2
Accept: application/json

###
GET http://localhost:3000/notes
Accept: application/json

###

GET http://localhost:3000/notes/stats
Accept: application/json

###


GET http://localhost:3000/notes/categories
Accept: application/json

###
